routes/web.php
<?php

Route::any('/', 'Front\FrontController@index');
Route::any('/npa/{npa_id}', 'Front\FrontController@npaPage');
Route::any('/institute/{institute_id}', 'Front\FrontController@institutePage');
Route::any('/institute/{institute_id}/discussion/{discuss_id}', 'Front\FrontController@discussPage');
Route::any('/doctrine/{position_id}', 'Front\FrontController@loadDoctrine');
Route::any('/contra_pos/{position_id}', 'Front\FrontController@contraPos');
Route::any('/position_text/{position_id}', 'Front\FrontController@posText');
Route::any('/team', 'Front\FrontController@Team');
Route::any('/base_docs', 'Front\FrontController@baseDocs');
Route::any('/faqs', 'Front\FrontController@Faqs');

Route::any('/loginform', 'Front\FrontController@loginForm')->name('loginform');
Route::any('/registration_form', 'Front\FrontController@registrationForm');
Route::any('/wall/{u_id}', 'Front\FrontController@publicProfile');

Route::any('/select2/institutes/{npa_id}', 'Front\FrontController@select2Institutes');
Route::any('/select2/npas', 'Front\FrontController@select2Npas');
Route::any('/inses_to_search/{npa_id}', 'Front\FrontController@insesToSearch');

Route::post('/front_register_post', 'Front\FrontController@frontReg');
Route::post('/reg/media', 'Front\FrontController@storeMedia')->name('front.reg.storeMedia');
Route::post('/front_login', 'Front\FrontController@frontLogin');



Route::group(['middleware' => ['authruslan']],
    function(){
    Route::any('/cabinet', 'Front\FrontController@cabinet');
    Route::any('/cabinet/positions', 'Front\FrontController@cabinetPositions');
    Route::resource('user', 'Front\FrontController');
    Route::post('/add_position', 'Front\FrontController@addPosition');
});

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Organizations
    Route::delete('organizations/destroy', 'OrganizationsController@massDestroy')->name('organizations.massDestroy');
    Route::resource('organizations', 'OrganizationsController');

    // Npas
    Route::delete('npas/destroy', 'NpaController@massDestroy')->name('npas.massDestroy');
    Route::post('npas/ckmedia', 'NpaController@storeCKEditorImages')->name('npas.storeCKEditorImages');
    Route::resource('npas', 'NpaController');

    // Institutes
    Route::delete('institutes/destroy', 'InstitutesController@massDestroy')->name('institutes.massDestroy');
    Route::post('institutes/media', 'InstitutesController@storeMedia')->name('institutes.storeMedia');
    Route::post('institutes/ckmedia', 'InstitutesController@storeCKEditorImages')->name('institutes.storeCKEditorImages');
    Route::resource('institutes', 'InstitutesController');

    // Discusses
    Route::delete('discusses/destroy', 'DiscussController@massDestroy')->name('discusses.massDestroy');
    Route::post('discusses/media', 'DiscussController@storeMedia')->name('discusses.storeMedia');
    Route::post('discusses/ckmedia', 'DiscussController@storeCKEditorImages')->name('discusses.storeCKEditorImages');
    Route::resource('discusses', 'DiscussController');

    // Law Systems
    Route::delete('law-systems/destroy', 'LawSystemController@massDestroy')->name('law-systems.massDestroy');
    Route::post('law-systems/media', 'LawSystemController@storeMedia')->name('law-systems.storeMedia');
    Route::post('law-systems/ckmedia', 'LawSystemController@storeCKEditorImages')->name('law-systems.storeCKEditorImages');
    Route::resource('law-systems', 'LawSystemController');

    // Positions
    Route::delete('positions/destroy', 'PositionsController@massDestroy')->name('positions.massDestroy');
    Route::post('positions/media', 'PositionsController@storeMedia')->name('positions.storeMedia');
    Route::post('positions/ckmedia', 'PositionsController@storeCKEditorImages')->name('positions.storeCKEditorImages');
    Route::resource('positions', 'PositionsController');

    // Arguments
    Route::delete('arguments/destroy', 'ArgumentsController@massDestroy')->name('arguments.massDestroy');
    Route::post('arguments/media', 'ArgumentsController@storeMedia')->name('arguments.storeMedia');
    Route::post('arguments/ckmedia', 'ArgumentsController@storeCKEditorImages')->name('arguments.storeCKEditorImages');
    Route::resource('arguments', 'ArgumentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Http/Controllers/Admin/DiscussController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyDiscussRequest;
use App\Http\Requests\StoreDiscussRequest;
use App\Http\Requests\UpdateDiscussRequest;
use App\Models\Discuss;
use App\Models\Institute;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class DiscussController extends Controller
{
    use MediaUploadingTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('discuss_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Discuss::with(['institute'])->select(sprintf('%s.*', (new Discuss)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'discuss_show';
                $editGate      = 'discuss_edit';
                $deleteGate    = 'discuss_delete';
                $crudRoutePart = 'discusses';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->addColumn('institute_name', function ($row) {
                return $row->institute ? $row->institute->name : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'institute']);

            return $table->make(true);
        }

        $institutes = Institute::get();

        return view('admin.discusses.index', compact('institutes'));
    }

    public function create()
    {
        abort_if(Gate::denies('discuss_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $institutes = Institute::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.discusses.create', compact('institutes'));
    }

    public function store(StoreDiscussRequest $request)
    {
        $discuss = Discuss::create($request->all());

        if ($request->input('avatar', false)) {
            $discuss->addMedia(storage_path('tmp/uploads/' . $request->input('avatar')))->toMediaCollection('avatar');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $discuss->id]);
        }

        return redirect()->route('admin.discusses.index');
    }

    public function edit(Discuss $discuss)
    {
        abort_if(Gate::denies('discuss_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $institutes = Institute::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $discuss->load('institute');

        return view('admin.discusses.edit', compact('institutes', 'discuss'));
    }

    public function update(UpdateDiscussRequest $request, Discuss $discuss)
    {
        $discuss->update($request->all());

        if ($request->input('avatar', false)) {
            if (!$discuss->avatar || $request->input('avatar') !== $discuss->avatar->file_name) {
                if ($discuss->avatar) {
                    $discuss->avatar->delete();
                }

                $discuss->addMedia(storage_path('tmp/uploads/' . $request->input('avatar')))->toMediaCollection('avatar');
            }
        } elseif ($discuss->avatar) {
            $discuss->avatar->delete();
        }

        return redirect()->route('admin.discusses.index');
    }

    public function show(Discuss $discuss)
    {
        abort_if(Gate::denies('discuss_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $discuss->load('institute', 'discussRulePositions');

        return view('admin.discusses.show', compact('discuss'));
    }

    public function destroy(Discuss $discuss)
    {
        abort_if(Gate::denies('discuss_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $discuss->delete();

        return back();
    }

    public function massDestroy(MassDestroyDiscussRequest $request)
    {
        Discuss::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('discuss_create') && Gate::denies('discuss_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Discuss();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/discusses/relationships/discussRulePositions.blade.php
@can('position_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.positions.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.position.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.position.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-discussRulePositions">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.position.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.position.fields.approved') }}
                        </th>
                        <th>
                            {{ trans('cruds.position.fields.author') }}
                        </th>
                        <th>
                            {{ trans('cruds.position.fields.title') }}
                        </th>
                        <th>
                            {{ trans('cruds.position.fields.discuss_rule') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($positions as $key => $position)
                        <tr data-entry-id="{{ $position->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $position->id ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\Position::APPROVED_SELECT[$position->approved] ?? '' }}
                            </td>
                            <td>
                                {{ $position->author->name ?? '' }}
                            </td>
                            <td>
                                {{ $position->title ?? '' }}
                            </td>
                            <td>
                                {{ $position->discuss_rule->name ?? '' }}
                            </td>
                            <td>
                                @can('position_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.positions.show', $position->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('position_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.positions.edit', $position->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('position_delete')
                                    <form action="{{ route('admin.positions.destroy', $position->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('position_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.positions.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 50,
  });
  let table = $('.datatable-discussRulePositions:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection